version: '3.9'

services:
  web_server:
    container_name: nginx
    image: nginx:1.23.2-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./app_laravel:/var/www/html

  mysql_db:
    container_name: mysql
    image: mysql:8.0.31
    restart: always
    tty: true
    ports:
      - 3306:3306
    networks:
      - app_network
    volumes:
      - mysql_8_db_vol:/var/lib/mysql
      # - ./docker/mysql-conf:/etc/mysql/conf.d
      # - ./mysql_local_db:/var/lib/mysql
      # command: >
      #           bash -c "mysqld --user=root --max_allowed_packet=32M"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: dipen
      MYSQL_PASSWORD: Admin@123

  php:
    build:
      context: ./
      dockerfile: Dockerfile-php
    depends_on:
      - mysql_db
    volumes:
      - ./app_laravel:/var/www/html
      - ./docker/php-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-error-reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  adminer:
    container_name: adminer
    depends_on:
      - mysql_db
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: root
      ADMINER_DEFAULT_SERVER: mysql
    networks:
      - app_network

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:


volumes:
  mysql_8_db_vol:
