version: '3'

networks:
  network:
  ## for now mysql_network
  ## available as dirName_network

# volumes: 
#   wp:
#   mysql_wp:

services:
  # Database
  db:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    networks:
      - network
    volumes:
      - ./docker/mysql_latest:/var/lib/mysql
      - ./env/mysqlconf:/etc/mysql/conf.d
    # command: >
    #           bash -c "mysqld --user=root --max_allowed_packet=32M"
    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: dipen
      MYSQL_PASSWORD: Admin@123


  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - network

## access mysql CLI
# docker exec -it mysql /bin/bash 
# mysql -p # password:root
# sudo rm -fr docker
# sudo rm -fr docker && docker-compose down
# sudo rm -fr docker && docker-compose down && docker-compose up --remove-orphan

## The server requested authentication method unknown to the client Solve
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';

## import data 
# docker exec -i  mysql mysql -u root -proot dbName < filename.sql
